name: Disparo Manual de Testes

on:
  workflow_dispatch:

jobs:
  k6-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Instalar K6
        run: |
          sudo apt-get update
          sudo apt-get install -y gnupg software-properties-common
          sudo wget -q -O - https://dl.k6.io/key.gpg | sudo apt-key add -
          echo "deb https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install -y k6

      - name: Subir API REST
        run: |
          npm run start-rest &   # comando para iniciar sua API
          sleep 5                # espera a API subir

      - name: Rodar testes K6
        run: |
          mkdir -p k6-reports
          k6 run \
            --env BASE_URL_REST=http://127.0.0.1:3000 \
            --out json=k6-reports/result.json \
            tests/k6/agendamentoLoad.k6.test.js

      - name: Instalar k6-to-html
        run: npm install -g k6-to-html

      - name: Gerar relatório HTML do K6
        run: k6-to-html k6-reports/result.json -o k6-reports/report.html

      - name: Salvar relatório JSON do K6 como artefato
        uses: actions/upload-artifact@v4
        with:
          name: k6-json-report
          path: k6-reports/result.json

      - name: Salvar relatório HTML do K6 como artefato
        uses: actions/upload-artifact@v4
        with:
          name: k6-html-report
          path: k6-reports/report.html
